#! /bin/bash

if [ -z "$1" ]; then
	echo "Error: missing SSID argument"
	echo "Usage: $(basename $0) <ssid>"
	echo
	exit -1
fi

while [ ! -z "$1" ]; do
	case $1 in
		-p|--vpn)
			shift
			ovpn_file="$1"
			;;
		*)
			SSID="$1"
			;;
	esac
done

SSID=$1

sudo ifconfig wlan0 up
if sudo iwlist wlan0 scan | grep "$SSID" -q; then
	echo "Connecting to $SSID..."
	sudo iwconfig wlan0 essid $SSID
	sudo dhclient wlan0
else
	echo "Error: $SSID not found!"
fi

if [ "$2" == "vpn" ]; then
	sudo service openvpn start
	sudo openvpn --config 
fi
